name: Build PHP 7

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [7.1, 7.0, 5.6]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring
          tools: phpunit:5.7.27
      
      - name: Execute Tests
        run: phpunit
