name: Build PHP 7,8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ${{ matrix.os }} 
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [ 8.0, 7.4, 7.3, 7.2]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring
          tools: phpunit:8.5.13
      
      - name: Execute Tests
        run: phpunit
      
      - name: CodeCov
        uses: codecov/codecov-action@v1
        
      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
        
