name: Build PHP 8.0

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy: 
      fail-fast: true
      matrix: 
        os: [ ubuntu-latest ]
        php: [ 8.0 ]
            
    name: PHP${{matrix.php}} - ${{matrix.os}}
    
    steps: 
      - name: Clone Repo
        uses: actions/checkout@v1
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }} 
          extensions: mysqli, mbstring, sqlsrv
          tools: phpunit:8.5.13
          
      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop
          
      - name: Install Dependencies
        run: composer install --prefer-source --no-interaction --no-dev
        
      - name: Execute Tests
        run: phpunit
      
      - name: CodeCov
        uses: codecov/codecov-action@v1   
