name: Build PHP 8.3

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
env:
  OPERATING_SYS: ubuntu-latest
  PHP_VERSION: 8.3
jobs:

  test:
    name: Run Tests
    uses: WebFiori/workflows/.github/workflows/test-php.yaml@main
    with:
      php-version: '8.3'
            

  code-coverage:
    name: Coverage
    needs: test
    uses: WebFiori/workflows/.github/workflows/coverage-codecov.yaml@main
    with:
      php-version: '8.3'
      coverage-file: 'php-8.3-coverage.xml'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}  

  code-quality:
    name: Code Quality
    needs: test
    uses: WebFiori/workflows/.github/workflows/quality-sonarcloud.yaml@main
    with:
      coverage-file: 'php-8.3-coverage.xml'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
  release_prod:
    name: Prepare Production Release Branch / Publish Release
    needs:
      - "test"
    runs-on: "ubuntu-latest"
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: php
          config-file: release-please-config.json
          token: ${{ secrets.GITHUB_TOKEN }}
