name: Build PHP 8.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  OPERATING_SYS: ubuntu-latest
  PHP_VERSION: 8.1
jobs:
  test:
    uses: WebFiori/workflows/.github/workflows/php-tests.yml@main
    with:
      php-version: ${{ env.PHP_VERSION }}

  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: CodeCov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          
